version: "3.5"

services:
  swamerai:
    image: swamerai
    container_name: swamerai
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3000:3000
    environment:
      - "NODE_ENV=development"
      - "AWS_REGION=localhost"
      - "AWS_ACCESS_KEY_ID=MOCK_ACCESS_KEY_ID"
      - "AWS_SECRET_ACCESS_KEY=MOCK_SECRET_ACCESS_KEY"
      - REDIS_URL=redis://cache

  prisma:
    container_name: swamerai_prisma
    image: prismagraphql/prisma:1.34
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: mysecret123
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo

  mongo:
    container_name: swamerai_mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    volumes:
      - ./data/mongo:/var/lib/mongo

  redis:
    container_name: swamerai_redis
    image: redis
    ports:
      - "6379:6379"

  s3:
    image: localstack/localstack:latest
    container_name: swamerai_s3
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './data/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  default:
    name: laguro_network
